# Generated by Django 3.2 on 2021-04-14 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('profile', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('enrollee_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=30)),
                ('enrolled_university', models.CharField(max_length=30)),
                ('education_level', models.CharField(max_length=30)),
                ('major_discipline', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('company_type', models.CharField(max_length=50)),
                ('lastnewjob', models.CharField(max_length=30)),
                ('training_hours', models.IntegerField()),
                ('target', models.IntegerField()),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.qualification')),
            ],
        ),
    ]
