# Generated by Django 3.2 on 2021-04-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_lastnewjob_employee_last_new_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
            preserve_default=False,
        ),
    ]
