# Generated by Django 3.2 on 2021-04-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_qualification_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
